package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Annex generated by hbm2java
 */
public class Annex implements java.io.Serializable {

	private Integer annexId;
	private String annexName;
	private String annexUrl;
	private Integer isAppear;
	private Integer browseTimes;
	private Integer loadTimes;
	private Set<Solution> solutions = new HashSet<Solution>(0);

	public Annex() {
	}

	public Annex(String annexName, String annexUrl, Integer isAppear,
			Integer browseTimes, Integer loadTimes, Set<Solution> solutions) {
		this.annexName = annexName;
		this.annexUrl = annexUrl;
		this.isAppear = isAppear;
		this.browseTimes = browseTimes;
		this.loadTimes = loadTimes;
		this.solutions = solutions;
	}

	public Integer getAnnexId() {
		return this.annexId;
	}

	public void setAnnexId(Integer annexId) {
		this.annexId = annexId;
	}

	public String getAnnexName() {
		return this.annexName;
	}

	public void setAnnexName(String annexName) {
		this.annexName = annexName;
	}

	public String getAnnexUrl() {
		return this.annexUrl;
	}

	public void setAnnexUrl(String annexUrl) {
		this.annexUrl = annexUrl;
	}

	public Integer getIsAppear() {
		return this.isAppear;
	}

	public void setIsAppear(Integer isAppear) {
		this.isAppear = isAppear;
	}

	public Integer getBrowseTimes() {
		return this.browseTimes;
	}

	public void setBrowseTimes(Integer browseTimes) {
		this.browseTimes = browseTimes;
	}

	public Integer getLoadTimes() {
		return this.loadTimes;
	}

	public void setLoadTimes(Integer loadTimes) {
		this.loadTimes = loadTimes;
	}

	public Set<Solution> getSolutions() {
		return this.solutions;
	}

	public void setSolutions(Set<Solution> solutions) {
		this.solutions = solutions;
	}

}
