package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Files generated by hbm2java
 */
public class Files implements java.io.Serializable {

	private Integer fileId;
	private Users usersByCreateUser;
	private Project project;
	private Users usersByCheckUser;
	private String fileName;
	private String fileDesc;
	private String createDate;
	private Integer checkStatus;
	private String checkDate;
	private Integer isAppear;
	private Integer loadTimes;
	private Integer browseTimes;
	private String fileType;
	private Set<FileKeyword> fileKeywords = new HashSet<FileKeyword>(0);
	private Set<Fileversion> fileversions = new HashSet<Fileversion>(0);

	public Files() {
	}

	public Files(Users usersByCreateUser, Project project,
			Users usersByCheckUser, String fileName, String fileDesc,
			String createDate, Integer checkStatus, String checkDate,
			Integer isAppear, Integer loadTimes, Integer browseTimes,
			String fileType, Set<FileKeyword> fileKeywords,
			Set<Fileversion> fileversions) {
		this.usersByCreateUser = usersByCreateUser;
		this.project = project;
		this.usersByCheckUser = usersByCheckUser;
		this.fileName = fileName;
		this.fileDesc = fileDesc;
		this.createDate = createDate;
		this.checkStatus = checkStatus;
		this.checkDate = checkDate;
		this.isAppear = isAppear;
		this.loadTimes = loadTimes;
		this.browseTimes = browseTimes;
		this.fileType = fileType;
		this.fileKeywords = fileKeywords;
		this.fileversions = fileversions;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public Users getUsersByCreateUser() {
		return this.usersByCreateUser;
	}

	public void setUsersByCreateUser(Users usersByCreateUser) {
		this.usersByCreateUser = usersByCreateUser;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Users getUsersByCheckUser() {
		return this.usersByCheckUser;
	}

	public void setUsersByCheckUser(Users usersByCheckUser) {
		this.usersByCheckUser = usersByCheckUser;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileDesc() {
		return this.fileDesc;
	}

	public void setFileDesc(String fileDesc) {
		this.fileDesc = fileDesc;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public Integer getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(String checkDate) {
		this.checkDate = checkDate;
	}

	public Integer getIsAppear() {
		return this.isAppear;
	}

	public void setIsAppear(Integer isAppear) {
		this.isAppear = isAppear;
	}

	public Integer getLoadTimes() {
		return this.loadTimes;
	}

	public void setLoadTimes(Integer loadTimes) {
		this.loadTimes = loadTimes;
	}

	public Integer getBrowseTimes() {
		return this.browseTimes;
	}

	public void setBrowseTimes(Integer browseTimes) {
		this.browseTimes = browseTimes;
	}

	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public Set<FileKeyword> getFileKeywords() {
		return this.fileKeywords;
	}

	public void setFileKeywords(Set<FileKeyword> fileKeywords) {
		this.fileKeywords = fileKeywords;
	}

	public Set<Fileversion> getFileversions() {
		return this.fileversions;
	}

	public void setFileversions(Set<Fileversion> fileversions) {
		this.fileversions = fileversions;
	}

}
