package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Functions generated by hbm2java
 */
public class Functions implements java.io.Serializable {

	private String functionId;
	private Module module;
	private String functionName;
	private String controlName;
	private Set<FunRole> funRoles = new HashSet<FunRole>(0);

	public Functions() {
	}

	public Functions(String functionId) {
		this.functionId = functionId;
	}

	public Functions(String functionId, Module module, String functionName,
			String controlName, Set<FunRole> funRoles) {
		this.functionId = functionId;
		this.module = module;
		this.functionName = functionName;
		this.controlName = controlName;
		this.funRoles = funRoles;
	}

	public String getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public String getFunctionName() {
		return this.functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	public String getControlName() {
		return this.controlName;
	}

	public void setControlName(String controlName) {
		this.controlName = controlName;
	}

	public Set<FunRole> getFunRoles() {
		return this.funRoles;
	}

	public void setFunRoles(Set<FunRole> funRoles) {
		this.funRoles = funRoles;
	}

}
