package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Keyword generated by hbm2java
 */
public class Keyword implements java.io.Serializable {

	private Integer keywordId;
	private Users users;
	private String keywordName;
	private Integer isDstroy;
	private String destroyDate;
	private Integer checkStatus;
	private String checkDate;
	private Integer searchTimes;
	private String createUser;
	private String keywordDesc;
	private String createDate;
	private Set<QuesKeyword> quesKeywords = new HashSet<QuesKeyword>(0);
	private Set<ProjectKeyword> projectKeywords = new HashSet<ProjectKeyword>(0);
	private Set<FileKeyword> fileKeywords = new HashSet<FileKeyword>(0);

	public Keyword() {
	}

	public Keyword(Users users, String keywordName, Integer isDstroy,
			String destroyDate, Integer checkStatus, String checkDate,
			Integer searchTimes, String createUser, String keywordDesc,
			String createDate, Set<QuesKeyword> quesKeywords,
			Set<ProjectKeyword> projectKeywords, Set<FileKeyword> fileKeywords) {
		this.users = users;
		this.keywordName = keywordName;
		this.isDstroy = isDstroy;
		this.destroyDate = destroyDate;
		this.checkStatus = checkStatus;
		this.checkDate = checkDate;
		this.searchTimes = searchTimes;
		this.createUser = createUser;
		this.keywordDesc = keywordDesc;
		this.createDate = createDate;
		this.quesKeywords = quesKeywords;
		this.projectKeywords = projectKeywords;
		this.fileKeywords = fileKeywords;
	}

	public Integer getKeywordId() {
		return this.keywordId;
	}

	public void setKeywordId(Integer keywordId) {
		this.keywordId = keywordId;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getKeywordName() {
		return this.keywordName;
	}

	public void setKeywordName(String keywordName) {
		this.keywordName = keywordName;
	}

	public Integer getIsDstroy() {
		return this.isDstroy;
	}

	public void setIsDstroy(Integer isDstroy) {
		this.isDstroy = isDstroy;
	}

	public String getDestroyDate() {
		return this.destroyDate;
	}

	public void setDestroyDate(String destroyDate) {
		this.destroyDate = destroyDate;
	}

	public Integer getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(String checkDate) {
		this.checkDate = checkDate;
	}

	public Integer getSearchTimes() {
		return this.searchTimes;
	}

	public void setSearchTimes(Integer searchTimes) {
		this.searchTimes = searchTimes;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getKeywordDesc() {
		return this.keywordDesc;
	}

	public void setKeywordDesc(String keywordDesc) {
		this.keywordDesc = keywordDesc;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public Set<QuesKeyword> getQuesKeywords() {
		return this.quesKeywords;
	}

	public void setQuesKeywords(Set<QuesKeyword> quesKeywords) {
		this.quesKeywords = quesKeywords;
	}

	public Set<ProjectKeyword> getProjectKeywords() {
		return this.projectKeywords;
	}

	public void setProjectKeywords(Set<ProjectKeyword> projectKeywords) {
		this.projectKeywords = projectKeywords;
	}

	public Set<FileKeyword> getFileKeywords() {
		return this.fileKeywords;
	}

	public void setFileKeywords(Set<FileKeyword> fileKeywords) {
		this.fileKeywords = fileKeywords;
	}

}
