package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

/**
 * QuesKeyword generated by hbm2java
 */
public class QuesKeyword implements java.io.Serializable {

	private Integer id;
	private Keyword keyword;
	private Questions questions;

	public QuesKeyword() {
	}

	public QuesKeyword(Keyword keyword, Questions questions) {
		this.keyword = keyword;
		this.questions = questions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Keyword getKeyword() {
		return this.keyword;
	}

	public void setKeyword(Keyword keyword) {
		this.keyword = keyword;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

}
