package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

/**
 * QuesSolu generated by hbm2java
 */
public class QuesSolu implements java.io.Serializable {

	private Integer id;
	private Solution solution;
	private Questions questions;

	public QuesSolu() {
	}

	public QuesSolu(Solution solution, Questions questions) {
		this.solution = solution;
		this.questions = questions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Solution getSolution() {
		return this.solution;
	}

	public void setSolution(Solution solution) {
		this.solution = solution;
	}

	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

}
