package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

/**
 * FunRole generated by hbm2java
 */
public class FunRole implements java.io.Serializable {

	private Integer id;
	private Functions functions;
	private Role role;

	public FunRole() {
	}

	public FunRole(Functions functions, Role role) {
		this.functions = functions;
		this.role = role;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Functions getFunctions() {
		return this.functions;
	}

	public void setFunctions(Functions functions) {
		this.functions = functions;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
