package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Integer projectId;
	private Project project;
	private String projectName;
	private String createTime;
	private String projectDesc;
	private String creater;
	private Set<ProjectKeyword> projectKeywords = new HashSet<ProjectKeyword>(0);
	private Set<Questions> questionses = new HashSet<Questions>(0);
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Project> projects_1 = new HashSet<Project>(0);
	private Set<Files> fileses = new HashSet<Files>(0);

	public Project() {
	}

	public Project(Project project, String projectName, String createTime,
			String projectDesc, String creater,
			Set<ProjectKeyword> projectKeywords, Set<Questions> questionses,
			Set<Project> projects, Set<Project> projects_1, Set<Files> fileses) {
		this.project = project;
		this.projectName = projectName;
		this.createTime = createTime;
		this.projectDesc = projectDesc;
		this.creater = creater;
		this.projectKeywords = projectKeywords;
		this.questionses = questionses;
		this.projects = projects;
		this.projects_1 = projects_1;
		this.fileses = fileses;
	}

	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	public String getCreater() {
		return this.creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	public Set<ProjectKeyword> getProjectKeywords() {
		return this.projectKeywords;
	}

	public void setProjectKeywords(Set<ProjectKeyword> projectKeywords) {
		this.projectKeywords = projectKeywords;
	}

	public Set<Questions> getQuestionses() {
		return this.questionses;
	}

	public void setQuestionses(Set<Questions> questionses) {
		this.questionses = questionses;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	public Set<Project> getProjects_1() {
		return this.projects_1;
	}

	public void setProjects_1(Set<Project> projects_1) {
		this.projects_1 = projects_1;
	}

	public Set<Files> getFileses() {
		return this.fileses;
	}

	public void setFileses(Set<Files> fileses) {
		this.fileses = fileses;
	}

}
