package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

/**
 * ProjectKeyword generated by hbm2java
 */
public class ProjectKeyword implements java.io.Serializable {

	private Integer id;
	private Keyword keyword;
	private Project project;

	public ProjectKeyword() {
	}

	public ProjectKeyword(Keyword keyword, Project project) {
		this.keyword = keyword;
		this.project = project;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Keyword getKeyword() {
		return this.keyword;
	}

	public void setKeyword(Keyword keyword) {
		this.keyword = keyword;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
