package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Questions generated by hbm2java
 */
public class Questions implements java.io.Serializable {

	private Integer questionId;
	private Users usersByWriteUser;
	private Project project;
	private Users usersByCheckUser;
	private String questionDesc;
	private String writeDate;
	private Integer checkStatus;
	private String checkDate;
	private Integer browseTimes;
	private String questionTitle;
	private Integer isSolve;
	private Set<QuesKeyword> quesKeywords = new HashSet<QuesKeyword>(0);
	private Set<QuesSolu> quesSolus = new HashSet<QuesSolu>(0);

	public Questions() {
	}

	public Questions(Users usersByWriteUser, Project project,
			Users usersByCheckUser, String questionDesc, String writeDate,
			Integer checkStatus, String checkDate, Integer browseTimes,
			String questionTitle, Integer isSolve,
			Set<QuesKeyword> quesKeywords, Set<QuesSolu> quesSolus) {
		this.usersByWriteUser = usersByWriteUser;
		this.project = project;
		this.usersByCheckUser = usersByCheckUser;
		this.questionDesc = questionDesc;
		this.writeDate = writeDate;
		this.checkStatus = checkStatus;
		this.checkDate = checkDate;
		this.browseTimes = browseTimes;
		this.questionTitle = questionTitle;
		this.isSolve = isSolve;
		this.quesKeywords = quesKeywords;
		this.quesSolus = quesSolus;
	}

	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	public Users getUsersByWriteUser() {
		return this.usersByWriteUser;
	}

	public void setUsersByWriteUser(Users usersByWriteUser) {
		this.usersByWriteUser = usersByWriteUser;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Users getUsersByCheckUser() {
		return this.usersByCheckUser;
	}

	public void setUsersByCheckUser(Users usersByCheckUser) {
		this.usersByCheckUser = usersByCheckUser;
	}

	public String getQuestionDesc() {
		return this.questionDesc;
	}

	public void setQuestionDesc(String questionDesc) {
		this.questionDesc = questionDesc;
	}

	public String getWriteDate() {
		return this.writeDate;
	}

	public void setWriteDate(String writeDate) {
		this.writeDate = writeDate;
	}

	public Integer getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(String checkDate) {
		this.checkDate = checkDate;
	}

	public Integer getBrowseTimes() {
		return this.browseTimes;
	}

	public void setBrowseTimes(Integer browseTimes) {
		this.browseTimes = browseTimes;
	}

	public String getQuestionTitle() {
		return this.questionTitle;
	}

	public void setQuestionTitle(String questionTitle) {
		this.questionTitle = questionTitle;
	}

	public Integer getIsSolve() {
		return this.isSolve;
	}

	public void setIsSolve(Integer isSolve) {
		this.isSolve = isSolve;
	}

	public Set<QuesKeyword> getQuesKeywords() {
		return this.quesKeywords;
	}

	public void setQuesKeywords(Set<QuesKeyword> quesKeywords) {
		this.quesKeywords = quesKeywords;
	}

	public Set<QuesSolu> getQuesSolus() {
		return this.quesSolus;
	}

	public void setQuesSolus(Set<QuesSolu> quesSolus) {
		this.quesSolus = quesSolus;
	}

}
