package com.loongsoft.knowledgebase.bean;

// Generated 2013-9-17 16:59:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Solution generated by hbm2java
 */
public class Solution implements java.io.Serializable {

	private Integer solutionId;
	private Users usersByWriteUser;
	private Annex annex;
	private Users usersByCheckUser;
	private String solutionContent;
	private String writeDate;
	private Integer checkStatus;
	private String checkDate;
	private String solutionName;
	private Set<QuesSolu> quesSolus = new HashSet<QuesSolu>(0);

	public Solution() {
	}

	public Solution(Users usersByWriteUser, Annex annex,
			Users usersByCheckUser, String solutionContent, String writeDate,
			Integer checkStatus, String checkDate, String solutionName,
			Set<QuesSolu> quesSolus) {
		this.usersByWriteUser = usersByWriteUser;
		this.annex = annex;
		this.usersByCheckUser = usersByCheckUser;
		this.solutionContent = solutionContent;
		this.writeDate = writeDate;
		this.checkStatus = checkStatus;
		this.checkDate = checkDate;
		this.solutionName = solutionName;
		this.quesSolus = quesSolus;
	}

	public Integer getSolutionId() {
		return this.solutionId;
	}

	public void setSolutionId(Integer solutionId) {
		this.solutionId = solutionId;
	}

	public Users getUsersByWriteUser() {
		return this.usersByWriteUser;
	}

	public void setUsersByWriteUser(Users usersByWriteUser) {
		this.usersByWriteUser = usersByWriteUser;
	}

	public Annex getAnnex() {
		return this.annex;
	}

	public void setAnnex(Annex annex) {
		this.annex = annex;
	}

	public Users getUsersByCheckUser() {
		return this.usersByCheckUser;
	}

	public void setUsersByCheckUser(Users usersByCheckUser) {
		this.usersByCheckUser = usersByCheckUser;
	}

	public String getSolutionContent() {
		return this.solutionContent;
	}

	public void setSolutionContent(String solutionContent) {
		this.solutionContent = solutionContent;
	}

	public String getWriteDate() {
		return this.writeDate;
	}

	public void setWriteDate(String writeDate) {
		this.writeDate = writeDate;
	}

	public Integer getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(Integer checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(String checkDate) {
		this.checkDate = checkDate;
	}

	public String getSolutionName() {
		return this.solutionName;
	}

	public void setSolutionName(String solutionName) {
		this.solutionName = solutionName;
	}

	public Set<QuesSolu> getQuesSolus() {
		return this.quesSolus;
	}

	public void setQuesSolus(Set<QuesSolu> quesSolus) {
		this.quesSolus = quesSolus;
	}

}
