// JavaScript Document
function switchNav(nav, mains) {
	switch (nav) {
	case ("nav" + 1):
		document.getElementById("iFrame1").src = "../jsp/QueryCheck.jsp";
	    document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
	    document.getElementById("nav14").style.background="url(../resource/images/navbackdown.jpg)";
		break;
	case ("nav" + 2):
		document.getElementById("iFrame1").src = "../jsp/CheckFile.jsp";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav14").style.background="url(../resource/images/navbackdown.jpg)";
		break;
	case ("nav" + 3):
		document.getElementById("iFrame1").src = "../jsp/CheckKeyWord.jsp";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav14").style.background="url(../resource/images/navbackdown.jpg)";
		break;
	case ("nav" + 4):
		document.getElementById("iFrame1").src = "../jsp/CheckSolu.jsp";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
   	 	document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
   	    document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav14").style.background="url(../resource/images/navbackdown.jpg)";
		break;
	case ("nav" + 5):
		document.getElementById("iFrame1").src = "../jsp/User.jsp";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
    	document.getElementById("nav13").style.background="url(../resource/images/navbackdown.jpg)";
    	document.getElementById("nav14").style.background="url(../resource/images/navbackup.jpg)";
		break;
	case ("nav" + 6):
		document.getElementById("iFrame1").src = "../jsp/Role.jsp";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav13").style.background="url(../resource/images/navbackdown.jpg)";
		document.getElementById("nav14").style.background="url(../resource/images/navbackup.jpg)";
		break;
	case ("nav" + 7):
		document.getElementById("iFrame1").src = "../jsp/Resource.jsp";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav13").style.background="url(../resource/images/navbackdown.jpg)";
		document.getElementById("nav14").style.background="url(../resource/images/navbackup.jpg)";
		break;
		
	case ("nav" + 8):
		document.getElementById("iFrame1").src = "../jsp/Home.jsp";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav8").style.background="url(../resource/images/navbackdown.jpg)";
		document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav14").style.background="url(../resource/images/navbackup.jpg)";
		break;
	case ("nav" + 9):
		document.getElementById("iFrame1").src = "/prokey/projectKeywordManage_getPro.action";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav9").style.background="url(../resource/images/navbackdown.jpg)";
		document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav14").style.background="url(../resource/images/navbackup.jpg)";
	    		
		break;
	case ("nav" + 10):
		document.getElementById("iFrame1").src = "/prokey/fileprokey_getPro.action";
		document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav10").style.background="url(../resource/images/navbackdown.jpg)";
		document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
		document.getElementById("nav14").style.background="url(../resource/images/navbackup.jpg)";
		break;
	case ("nav" + 11):
		document.getElementById("iFrame1").src = "/project/project_list.action";
	document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav11").style.background="url(../resource/images/navbackdown.jpg)";
	document.getElementById("nav12").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav14").style.background="url(../resource/images/navbackup.jpg)";
		break;
	case ("nav" + 12):
		document.getElementById("iFrame1").src = "../jsp/KeyWord.jsp";
	document.getElementById("nav1").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav2").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav3").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav4").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav5").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav6").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav7").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav8").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav9").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav10").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav11").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav12").style.background="url(../resource/images/navbackdown.jpg)";
	document.getElementById("nav13").style.background="url(../resource/images/navbackup.jpg)";
	document.getElementById("nav14").style.background="url(../resource/images/navbackup.jpg)";
		break;
	}
}